### ISSUE TITLE
로고디자인

### ISSUE THREAD

**Issue by iworkist** [daejeonpython/meerkats#15]
meerkats 대시보드의 로고 디자인 만들기

**Comment by nqn4iwin** [comment]
애니메이션 로고 - 평범한 원형이었다가 마우스 커서 올리면 동물 이미지로 변환(망원경)

참고 사이트
https://blog.naver.com/PostView.nhn?isHttpsRedirect=true&blogId=imagine0716&logNo=221036010275

**Comment by nqn4iwin** [comment]
logo repository에서 완료됨

**Comment by nqn4iwin** [comment]
logo repository에서 완료함
