### ISSUE TITLE
엘라스틱서치 'oie_reports_kr' 인덱스 확인 요청

### ISSUE THREAD

**Issue by eungiHong** [daejeonpython/meerkats#18]
어제 MySQL에 있는 데이터를 엘라스틱서치에 입력하였습니다. 총 45개 column 중 추출한 column은 9개로 아래와 같습니다.

1. 발생일 (Date of start of the outbreak)
2. 질병 (Disease)
3. 혈청형 (Serotype)
4. 축종 (SPECIES)
5. 구분
6. 건수 (Number of outbreaks)
7. 국가 (Country)
8. 발생지역 (Region)
9. 위경도 (geolocation)

비고:
1) '구분'은 해당 동물이 사육인지 야생인지를 나타냅니다.
2) 약 45,000개의 행을 입력하였고, 앞으로 추가되는 데이터는 DB - Elasticsearch 간 동기화 코드를 구현 후에 추가할 예정입니다.

**Comment by hhongjoon** [comment]
위경도 데이터 Kibana에서 Geospatial field로 인식방법 확인중입니다.

**Comment by hhongjoon** [comment]
"위경도": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword", -->  **"type": "geo_point" 변경필요**
              "ignore_above": 256
            }
          }
        },

**Comment by hhongjoon** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html

입력텍스트는 4번에 해당할듯하네요

**Comment by eungiHong** [comment]
기존에 생성했던 "oie_reports_kr" 인덱스의 문제점:
1. _id를 별도 지정하지 않음 -> 새로운 데이터를 덮어쓸 때 id를 알 수 없어 업데이트 불가능
2. 위경도 type을 text로 지정

수정사항:
1. id 별도 지정
2. 위경도 type을 geo_point로 지정 (홍준님께 감사)

변경사항 반영하여 oie_reports_kr_ver2 인덱스 새로 생성 완료 (기존 "oie_reports_kr" 인덱스를 수정해서 쓰기는 좀 어려울듯...)

**Comment by eungiHong** [comment]
# 기존에 생성했던 "oie_reports_kr" 인덱스의 문제점:
1. id를 별도 지정하지 않음 -> 새로운 데이터를 덮어쓸 때 id를 알 수 없어 업데이트 불가능
2. 위경도 type을 text로 지정

# 수정사항:
1. id 별도 지정
2. 위경도 type을 geo_point로 지정 (@hhongjoon 님께 감사)

변경사항 반영하여 oie_reports_kr_ver2 인덱스 새로 생성 완료 (기존 "oie_reports_kr" 인덱스를 수정해서 쓰기는 좀 어려울듯...)

# 개선할 점 제안
1. 현재 id 지정한 방식이 단순히 row number를 가지고 지정했는데, 이렇게 할 경우 db의 데이터 일부가 삭제되었을 경우, id 체계가 망가지는 문제 발생함
2. 따라서, db에 각 row에 대한 고유 id를 지정하는 ID column을 별도로 만들어야 할듯 (@vet-Q  이미 있다면 설명 부탁 드립니다 ㅜ)
3. @vet-Q  또한, 현재 collector에서 기존 row와 신규 row를 어떻게 비교하고 있는지 여쭤봐도 될까요?

**Comment by vet-Q** [comment]
1. 맞습니다. 자동번호 지정이 될 경우 중간 행 삭제시 문제가 될 가능성이 있습니다
2. 고유id는 리포트 번호 컬럼으로 설정되 있는데 연번이 아닌 문제가 있습니다.ㅠ

3. 리포트 번호를 읽어와서 중복번호 제거 후 최근 1주일 간의 리포트 번호 100개와 대조해서 새로운 것을 신규 건으로 간주합니다

++) geo-point 데이터 타입으로 설정하면 바로 인식이 되나요?? 리스트로 한 셀에 넣으려 하니 판다스가 자동으로 2행으로 잡는 문제가 있어 str처리 하였습니다 여쭤보고 할걸 그랬네요

**Comment by eungiHong** [comment]
1. MySQL db (oie_reports_kr)의 **rowid** (unique id) -> ES index (oie_reports_kr_ver2)의 **_id** 매핑 완료
2. ES index (oie_reports_kr_ver2)에 '지역'(유럽, 아시아 등) 필드 추가 완료
3. 신규 수집 데이터 -> ES index (oie_reports_kr_ver2) 업데이트 완료 (5만행 -> 10만행)
