### ISSUE TITLE
연습용 이슈 만들기

### ISSUE THREAD

**Issue by iworkist** [daejeonpython/meerkats#6]
이슈 시스템을 이해하기위해
assignees에 할당된 멤버는 연습용 이슈를 만들어봅니다.

**Comment by Ki-Hwan-Park** [comment]
Oh;; Re-assignment me please. I made a mistake.

**Comment by iworkist** [comment]
> Oh;; Re-assignment me please. I made a mistake.


@Ki-Hwan-Park 
assignment 했습니다.

**Comment by Ki-Hwan-Park** [comment]
> > Oh;; Re-assignment me please. I made a mistake.
> 
> @Ki-Hwan-Park
> assignment 했습니다.

@iworkist 
감사합니다..!

**Comment by nqn4iwin** [comment]
assignment 감사합니다! 이런식으로 하면 되는건가요?

**Comment by iworkist** [comment]
> assignment 감사합니다! 이런식으로 하면 되는건가요?

![image](https://user-images.githubusercontent.com/10336572/128662039-1532ede5-1046-47d1-bd8f-30bde0ae5a8b.png)

[new issue] 버튼을 클릭해서 이슈를 하나 만들어보세요.
