### ISSUE TITLE
meerkats repo access

### ISSUE THREAD

**Issue by hhongjoon** [daejeonpython/meerkats#9]
clone후에 테스트커밋중인데 push에서 막힙니다.
meerkats 레포지토리에 commit 권한이 없는건가요?

Password for 'https://hhongjoon@github.com':
remote: Permission to daejeonpython/meerkats.git denied to hhongjoon.
fatal: unable to access 'https://github.com/daejeonpython/meerkats.git/': The requested URL returned error: 403

**Comment by iworkist** [comment]
meerkats에 멤버추가가 안되어 있었네요.
멤버추가했으니 push 해보시기 바랍니다.

**Comment by hhongjoon** [comment]
감사합니다.
